[package]
name = "polysock"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
derive_builder = "0.20.2"
io-pipe = "0.7.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
